Update deploy_to_gh_pages.yaml

diff --git a/.github/workflows/deploy_to_gh_pages.yaml b/.github/workflows/deploy_to_gh_pages.yaml
--- a/.github/workflows/deploy_to_gh_pages.yaml
+++ b/.github/workflows/deploy_to_gh_pages.yaml
@@ -2,6 +2,8 @@ name: "Build and deploy to GH pages site"
 
 on:
   push:
+    branches:
+      - main, gh-page-deploy
 
 permissions: 
   contents: write
@@ -12,6 +14,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check if we should deploy...
+        run: |
+          if ["${{env.RUN_DEPLOY_GH_ACTION}}" != "true" ]; then
+            echo "Error: RUN_DEPLOY_GH_ACTION is set not set to true..." 
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v4
 
